### PR TITLE
Add Ukrainian translation and navigation

### PR DESCRIPTION
**Pull request by NazarPonochevnyi**
Added Ukrainian translation and navigation to the translation.

### CODE REVIEW

**Comment by tshemsedinov** [comment]
@NazarPonochevnyi please contact @litashg to merge with #2

**Comment by NazarPonochevnyi** [comment]
Я поправил)

**Comment by NazarPonochevnyi** [comment]
Все готово к мержу с мастером!)

**Comment by NazarPonochevnyi** [comment]
I'm created line breaks.

**Comment by tshemsedinov** [comment]
I'll merge everything and add insert commit with english version before translation to compare

**Comment by NazarPonochevnyi** [comment]
Ok

**Comment by tshemsedinov** [comment]
Landed in e4c2384a23f8af956e6416d94d7df270cfa34412, efdfce368f8589adb3fd7630ebaf3a2e237fde21, d95312bc9418169d666176fff5b9372755fd107b and 6f73e53baa1b2be914dda01b2e7e31a1955e2bf4

**Pull request closed without merging**
